#!/bin/sh
export HOME=/
export RUBY_HEAP_MIN_SLOTS=${RUBY_HEAP_MIN_SLOTS-600000}
export RUBY_GC_MALLOC_LIMIT=${RUBY_GC_MALLOC_LIMIT-59000000}
export RUBY_HEAP_FREE_MIN=${RUBY_HEAP_FREE_MIN-100000}
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=${RUBY_HEAP_SLOTS_GROWTH_FACTOR-1}
export RUBY_HEAP_SLOTS_INCREMENT=${RUBY_HEAP_SLOTS_INCREMENT-250000}
exec setuidgid puppet /opt/puppet-omnibus/embedded/bin/unicorn \
                        -c /opt/puppet-omnibus/etc/unicorn.conf \
                        -E deployment "$@"
