source "https://rubygems.org"

# TODO: why do we need all of this?
gem 'nokogiri',     '1.4.4'
gem 'facter',       '2.0.2'
gem 'json',         '1.8.0'
gem 'hiera',        '1.3.4'
gem 'deep_merge',   '1.0.0'
gem 'rgen',         '0.6.5'
gem 'ruby-augeas',  '0.4.1'
gem 'ruby-shadow',  '2.2.0'
gem 'gpgme',        '2.0.5'
gem 'highline',     '1.6.21' # Ruby
gem 'trollop',      '2.0'    # ??? FIXME
gem 'hiera-eyaml',  '2.0.2'  # MIT
gem 'rack',         '1.5.2'
gem 'unicorn',      '4.8.3'
gem 'puppet',       '3.6.2'

group :frc do
  gem 'ruby-libvirt', '0.4.0'
end
