source "http://rubygems.org"

# Main section
# TODO: why do we need all of this?
gem 'nokogiri',               '1.5.11'
gem 'facter',                 '2.1.0'
gem 'json',                   '1.8.1'
gem 'hiera',                  '1.3.4'
gem 'deep_merge',             '1.0.0'
gem 'rgen',                   '0.6.6'
gem 'ruby-augeas',            '0.4.1'
gem 'ruby-shadow',            '2.2.0'
gem 'gpgme',                  '2.0.5'
gem 'highline',               '1.6.21'     # Ruby
gem 'trollop',                '2.0'        # ??? FIXME
gem 'hiera-eyaml',            '2.0.2'      # MIT
gem 'rack',                   '1.5.2'
gem 'unicorn',                '4.8.3'

group :centos_6 do
  gem 'ruby-libvirt',         '0.4.0'
end

# Puppet tools section
gem 'puppet-syntax', '1.2.0'
gem 'puppet-lint', '~> 1.1.0'              # MIT

# AWS section
gem 'unf',                    '0.1.3'
gem 'aws-sdk',                '1.55.0'
gem 'fog',                    '1.19.0'
