source "https://rubygems.org"

# Main section
# TODO: why do we need all of this?
gem 'nokogiri',               '1.5.11'
gem 'facter',                 '2.0.2'
gem 'json',                   '1.8.1'
gem 'hiera',                  '1.3.4'
gem 'deep_merge',             '1.0.0'
gem 'rgen',                   '0.6.6'
gem 'ruby-augeas',            '0.4.1'
gem 'ruby-shadow',            '2.2.0'
gem 'gpgme',                  '2.0.5'
gem 'highline',               '1.6.21'     # Ruby
gem 'trollop',                '2.0'        # ??? FIXME
gem 'hiera-eyaml',            '2.0.2'      # MIT
gem 'rack',                   '1.5.2'
gem 'unicorn',                '4.8.3'
gem 'puppet',                 '3.6.2'

group :centos_6 do
  gem 'ruby-libvirt',         '0.4.0'
end

# Puppet tools section
# TODO: Is this really needed?
gem 'puppet-syntax',          '1.1.0'      # MIT
gem 'librarian-puppet',       '0.9.10'     # Ruby
gem 'rspec-core',             '2.14.5'     # MIT
gem 'rspec-expectations',     '2.14.2'     # MIT
gem 'rspec-mocks',            '2.14.3'     # MIT
gem 'rspec',                  '2.14.1'     # MIT
gem 'rake-hooks',             '1.2.3'      # MIT
gem 'rspec-puppet',           '1.0.1'      # MIT
gem 'puppetlabs_spec_helper', '0.4.1'      # Apache2
gem 'sensu-plugin',           '0.2.2'
gem 'puppet-lint',            '0.4.0.pre1'
gem 'r10k',                   '1.2.0'

# AWS section
gem 'unf',                    '0.1.3'
gem 'aws-sdk',                '1.33.0'
gem 'fog',                    '1.19.0'
