#!/usr/bin/env bash
unset RUBYOPT BUNDLE_GEMFILE BUNDLE_BIN_PATH GEM_HOME GEM_PATH GEMRC

# this is because of exceccive calls to stat /etc/localtime
export TZ=PDT

export RUBY_GC_HEAP_INIT_SLOTS=600000
export RUBY_GC_HEAP_FREE_SLOTS=300000
export RUBY_GC_HEAP_GROWTH_FACTOR=1.2
export RUBY_GC_HEAP_GROWTH_MAX_SLOTS=125000
export RUBY_GC_MALLOC_LIMIT=64000000
export RUBY_GC_OLDMALLOC_LIMIT=64000000
export PATH="/opt/puppet-omnibus/embedded/bin:$PATH"

exec /opt/puppet-omnibus/embedded/bin/puppet "$@"
