#!/bin/sh
unset RUBYOPT BUNDLE_GEMFILE BUNDLE_BIN_PATH GEM_HOME GEM_PATH GEMRC

export HOME=/
export RUBY_GC_HEAP_INIT_SLOTS=${RUBY_GC_HEAP_INIT_SLOTS-250000}
export RUBY_GC_HEAP_FREE_SLOTS=${RUBY_GC_HEAP_FREE_SLOTS-250000}
export RUBY_GC_HEAP_GROWTH_FACTOR=${RUBY_GC_HEAP_GROWTH_FACTOR-1.1}
export RUBY_GC_HEAP_GROWTH_MAX_SLOTS=${RUBY_GC_HEAP_GROWTH_MAX_SLOTS-150000}
export RUBY_GC_MALLOC_LIMIT=${RUBY_GC_MALLOC_LIMIT-64000000}
export RUBY_GC_OLDMALLOC_LIMIT=${RUBY_GC_OLDMALLOC_LIMIT-64000000}
export PATH="/opt/puppet-omnibus/embedded/bin:$PATH"

exec nice -n +10 setuidgid puppet /opt/puppet-omnibus/embedded/bin/unicorn \
                        -c /opt/puppet-omnibus/etc/unicorn.conf \
                        -E deployment "$@"
